services:
  application:
    image: elixir_practice:0.0.1
    container_name: elixir_practice
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/elixir_practice_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:14-bookworm
    container_name: elixir_practice-postgres
    environment:
      - POSTGRES_DB=elixir_practice_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - elixir_practice_psql:/var/lib/postgresql/data
volumes:
  elixir_practice_psql:
